# permissions for end users to view labels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: labels-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: node-label-operator
    app.kubernetes.io/part-of: node-label-operator
    app.kubernetes.io/managed-by: kustomize
  name: labels-viewer-role
rules:
- apiGroups:
  - node-labels.cfy.cz
  resources:
  - labels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - node-labels.cfy.cz
  resources:
  - labels/status
  verbs:
  - get
