# permissions for end users to edit labels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: label-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: node-label-operator
    app.kubernetes.io/part-of: node-label-operator
    app.kubernetes.io/managed-by: kustomize
  name: label-editor-role
rules:
- apiGroups:
  - node-labels.cfy.cz
  resources:
  - labels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - node-labels.cfy.cz
  resources:
  - labels/status
  verbs:
  - get
