apiVersion: node-labels.cfy.cz/v1
kind: Labels
metadata:
  labels:
    app.kubernetes.io/name: labels
    app.kubernetes.io/instance: labels-sample
    app.kubernetes.io/part-of: node-label-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: node-label-operator
  name: labels-sample
spec:
  # TODO(user): Add fields here
